import { ICarModels, IService } from "@/interfaces/form";
export const years = [
  {
    value: "year",
    text: "Choose Year",
    // disabled: true,
    // selected: true,
    hidden: true,
  },
  { value: "1970", text: "1970" },
  { value: "1971", text: "1971" },
  { value: "1972", text: "1972" },
  { value: "1973", text: "1973" },
  { value: "1974", text: "1974" },
  { value: "1975", text: "1975" },
  { value: "1976", text: "1976" },
  { value: "1977", text: "1977" },
  { value: "1978", text: "1978" },
  { value: "1979", text: "1979" },
  { value: "1980", text: "1980" },
  { value: "1981", text: "1981" },
  { value: "1982", text: "1982" },
  { value: "1983", text: "1983" },
  { value: "1984", text: "1984" },
  { value: "1985", text: "1985" },
  { value: "1986", text: "1986" },
  { value: "1987", text: "1987" },
  { value: "1988", text: "1988" },
  { value: "1989", text: "1989" },
  { value: "1990", text: "1990" },
  { value: "1991", text: "1991" },
  { value: "1992", text: "1992" },
  { value: "1993", text: "1993" },
  { value: "1994", text: "1994" },
  { value: "1995", text: "1995" },
  { value: "1996", text: "1996" },
  { value: "1997", text: "1997" },
  { value: "1998", text: "1998" },
  { value: "1999", text: "1999" },
  { value: "2000", text: "2000" },
  { value: "2001", text: "2001" },
  { value: "2002", text: "2002" },
  { value: "2003", text: "2003" },
  { value: "2004", text: "2004" },
  { value: "2005", text: "2005" },
  { value: "2006", text: "2006" },
  { value: "2007", text: "2007" },
  { value: "2008", text: "2008" },
  { value: "2009", text: "2009" },
  { value: "2010", text: "2010" },
  { value: "2011", text: "2011" },
  { value: "2012", text: "2012" },
  { value: "2013", text: "2013" },
  { value: "2014", text: "2014" },
  { value: "2015", text: "2015" },
  { value: "2016", text: "2016" },
  { value: "2017", text: "2017" },
  { value: "2018", text: "2018" },
  { value: "2019", text: "2019" },
  { value: "2020", text: "2020" },
  { value: "2021", text: "2021" },
  { value: "2022", text: "2022" },
  { value: "2023", text: "2023" },
];

export const carBrands = [
  {
    value: "make",
    text: "Choose your make",
    // disabled: true,
    // selected: true,
    hidden: true,
  },
  { value: "acura", text: "Acura" },
  { value: "alfaRomeo", text: "Alfa Romeo" },
  { value: "astonMartin", text: "Aston Martin" },
  { value: "audi", text: "Audi" },
  // { value: "bmw", text: "BMW" },
  // { value: "bentley", text: "Bentley" },
  // { value: "bugatti", text: "Bugatti" },
  // { value: "buick", text: "Buick" },
  // { value: "cadillac", text: "Cadillac" },
  // { value: "chevrolet", text: "Chevrolet" },
  // { value: "chrysler", text: "Chrysler" },
  // { value: "daewoo", text: "Daewoo" },
  // { value: "dodge", text: "Dodge" },
  // { value: "eagle", text: "Eagle" },
  // { value: "smart", text: "smart" },
  // { value: "fiat", text: "FIAT" },
  // { value: "ferrari", text: "Ferrari" },
  // { value: "fisker", text: "Fisker" },
  // { value: "ford", text: "Ford" },
  // { value: "gmc", text: "GMC" },
  // { value: "geo", text: "Geo" },
  // { value: "hummer", text: "HUMMER" },
  // { value: "honda", text: "Honda" },
  // { value: "hyundai", text: "Hyundai" },
  // { value: "infiniti", text: "Infiniti" },
  // { value: "isuzu", text: "Isuzu" },
  // { value: "jaguar", text: "Jaguar" },
  // { value: "jeep", text: "Jeep" },
  // { value: "kia", text: "Kia" },
  // { value: "lamborghini", text: "Lamborghini" },
  // { value: "landRover", text: "Land Rover" },
  // { value: "lexus", text: "Lexus" },
  // { value: "lincoln", text: "Lincoln" },
  // { value: "lotus", text: "Lotus" },
  // { value: "mini", text: "MINI" },
  // { value: "maserati", text: "Maserati" },
  // { value: "maybach", text: "Maybach" },
  // { value: "mazda", text: "Mazda" },
  // { value: "mclaren", text: "McLaren" },
  // { value: "mercedesBenz", text: "Mercedes-Benz" },
  // { value: "mercury", text: "Mercury" },
  // { value: "mitsubishi", text: "Mitsubishi" },
  // { value: "nissan", text: "Nissan" },
  // { value: "oldsmobile", text: "Oldsmobile" },
  // { value: "panoz", text: "Panoz" },
  // { value: "plymouth", text: "Plymouth" },
  // { value: "pontiac", text: "Pontiac" },
  // { value: "porsche", text: "Porsche" },
  // { value: "ram", text: "Ram" },
  // { value: "rollsRoyce", text: "Rolls-Royce" },
  // { value: "saab", text: "Saab" },
  // { value: "saturn", text: "Saturn" },
  // { value: "scion", text: "Scion" },
  // { value: "spyker", text: "Spyker" },
  // { value: "subaru", text: "Subaru" },
  // { value: "suzuki", text: "Suzuki" },
  // { value: "tesla", text: "Tesla" },
  // { value: "toyota", text: "Toyota" },
  // { value: "volkswagen", text: "Volkswagen" },
  // { value: "volvo", text: "Volvo" },
];

export const models: ICarModels = {
  default: [
    {
      value: "make",
      text: "First, choose a car make. ",
      disabled: true,
      hidden: true,
    },
  ],
  acura: [
    {
      value: "make",
      text: "Choose model",
      hidden: true,
    },
    { value: "cl", text: "CL" },
    { value: "ilx", text: "ILX" },
    { value: "integra", text: "Integra" },
    { value: "legend", text: "Legend" },
    { value: "mdx", text: "MDX" },
    { value: "nsx", text: "NSX" },
    { value: "rdx", text: "RDX" },
    { value: "rl", text: "RL" },
    { value: "rlx", text: "RLX" },
    { value: "rsx", text: "RSX" },
    { value: "slx", text: "SLX" },
    { value: "tl", text: "TL" },
    { value: "tlx", text: "TLX" },
    { value: "tsx", text: "TSX" },
    { value: "vigor", text: "Vigor" },
    { value: "zdx", text: "ZDX" },
  ],
  alfaRomeo: [
    {
      value: "make",
      text: "Choose model",
      hidden: true,
    },
    { value: "4c", text: "4C" },
    { value: "giulia", text: "Giulia" },
    { value: "giulietta", text: "Giulietta" },
    { value: "stelvio", text: "Stelvio" },
    { value: "gt", text: "GT" },
    { value: "gta", text: "GTA" },
    { value: "spider", text: "Spider" },
    { value: "156", text: "156" },
    { value: "159", text: "159" },
    { value: "166", text: "166" },
    { value: "brera", text: "Brera" },
    { value: "gtv", text: "GTV" },
    { value: "mito", text: "MiTo" },
  ],
  astonMartin: [
    {
      value: "make",
      text: "Choose model",
      hidden: true,
    },
    { value: "db11", text: "DB11" },
    { value: "db9", text: "DB9" },
    { value: "dbs", text: "DBS" },
    { value: "vantage", text: "Vantage" },
    { value: "rapide", text: "Rapide" },
    { value: "valkyrie", text: "Valkyrie" },
    { value: "virage", text: "Virage" },
    { value: "one77", text: "One-77" },
    { value: "lagonda", text: "Lagonda" },
    { value: "cygnet", text: "Cygnet" },
  ],
  audi: [
    {
      value: "make",
      text: "Choose model",
      hidden: true,
    },
    { value: "a1", text: "A1" },
    { value: "a2", text: "A2" },
    { value: "a3", text: "A3" },
    { value: "a4", text: "A4" },
    { value: "a5", text: "A5" },
    { value: "a6", text: "A6" },
    { value: "a7", text: "A7" },
    { value: "a8", text: "A8" },
    { value: "q2", text: "Q2" },
    { value: "q3", text: "Q3" },
    { value: "q4", text: "Q4" },
    { value: "q5", text: "Q5" },
    { value: "q6", text: "Q6" },
    { value: "q7", text: "Q7" },
    { value: "q8", text: "Q8" },
    { value: "r8", text: "R8" },
    { value: "etron", text: "e-tron" },
    { value: "etronGT", text: "e-tron GT" },
    { value: "s3", text: "S3" },
    { value: "s4", text: "S4" },
    { value: "s5", text: "S5" },
    { value: "s6", text: "S6" },
    { value: "s7", text: "S7" },
    { value: "s8", text: "S8" },
    { value: "tt", text: "TT" },
  ],
};

export const services: IService[] = [
  { value: "trailerHitch", text: "Trailer Hitch" },
  { value: "bedCover", text: "Bed Cover" },
  { value: "patriotLiner", text: "Patriot Liner" },
  { value: "suspension", text: "Suspension" },
  { value: "rustPrevention", text: "Rust Prevention" },
  { value: "ceramicCoating", text: "Ceramic Coating" },
  { value: "ppf", text: "PPF (Clear Bra)" },
  { value: "detailing", text: "Detailing" },
  { value: "vanPackages", text: "Van Packages" },
  { value: "fleetManagement", text: "Fleet Management" },
  { value: "otherService", text: "Other Service" },
];

export const states = [
  {
    value: "state",
    text: "State",
    hidden: true,
  },
  { value: "AL", text: "AL" },
  { value: "AK", text: "AK" },
  { value: "AZ", text: "AZ" },
  { value: "AR", text: "AR" },
  { value: "CA", text: "CA" },
  { value: "CO", text: "CO" },
  { value: "CT", text: "CT" },
  { value: "DE", text: "DE" },
  { value: "FL", text: "FL" },
  { value: "GA", text: "GA" },
  { value: "HI", text: "HI" },
  { value: "ID", text: "ID" },
  { value: "IL", text: "IL" },
  { value: "IN", text: "IN" },
  { value: "IA", text: "IA" },
  { value: "KS", text: "KS" },
  { value: "KY", text: "KY" },
  { value: "LA", text: "LA" },
  { value: "ME", text: "ME" },
  { value: "MD", text: "MD" },
  { value: "MA", text: "MA" },
  { value: "MI", text: "MI" },
  { value: "MN", text: "MN" },
  { value: "MS", text: "MS" },
  { value: "MO", text: "MO" },
  { value: "MT", text: "MT" },
  { value: "NE", text: "NE" },
  { value: "NV", text: "NV" },
  { value: "NH", text: "NH" },
  { value: "NJ", text: "NJ" },
  { value: "NM", text: "NM" },
  { value: "NY", text: "NY" },
  { value: "NC", text: "NC" },
  { value: "ND", text: "ND" },
  { value: "OH", text: "OH" },
  { value: "OK", text: "OK" },
  { value: "OR", text: "OR" },
  { value: "PA", text: "PA" },
  { value: "RI", text: "RI" },
  { value: "SC", text: "SC" },
  { value: "SD", text: "SD" },
  { value: "TN", text: "TN" },
  { value: "TX", text: "TX" },
  { value: "UT", text: "UT" },
  { value: "VT", text: "VT" },
  { value: "VA", text: "VA" },
  { value: "WA", text: "WA" },
  { value: "WV", text: "WV" },
  { value: "WI", text: "WI" },
  { value: "WY", text: "WY" },
];
