import { ICarModels, IService } from "../../interfaces/form";

export const models: ICarModels = {
  default: [
    {
      value: "make",
      text: "First, choose a car make. ",
      disabled: true,
      hidden: true,
    },
  ],
  acura: [
    {
      value: "make",
      text: "Choose model",
      hidden: true,
    },
    { value: "cl", text: "CL" },
    { value: "ilx", text: "ILX" },
    { value: "integra", text: "Integra" },
    { value: "legend", text: "Legend" },
    { value: "mdx", text: "MDX" },
    { value: "nsx", text: "NSX" },
    { value: "rdx", text: "RDX" },
    { value: "rl", text: "RL" },
    { value: "rlx", text: "RLX" },
    { value: "rsx", text: "RSX" },
    { value: "slx", text: "SLX" },
    { value: "tl", text: "TL" },
    { value: "tlx", text: "TLX" },
    { value: "tsx", text: "TSX" },
    { value: "vigor", text: "Vigor" },
    { value: "zdx", text: "ZDX" },
  ],
  alfaRomeo: [
    {
      value: "make",
      text: "Choose model",
      hidden: true,
    },
    { value: "4c", text: "4C" },
    { value: "giulia", text: "Giulia" },
    { value: "giulietta", text: "Giulietta" },
    { value: "stelvio", text: "Stelvio" },
    { value: "gt", text: "GT" },
    { value: "gta", text: "GTA" },
    { value: "spider", text: "Spider" },
    { value: "156", text: "156" },
    { value: "159", text: "159" },
    { value: "166", text: "166" },
    { value: "brera", text: "Brera" },
    { value: "gtv", text: "GTV" },
    { value: "mito", text: "MiTo" },
  ],
  astonMartin: [
    {
      value: "make",
      text: "Choose model",
      hidden: true,
    },
    { value: "db11", text: "DB11" },
    { value: "db9", text: "DB9" },
    { value: "dbs", text: "DBS" },
    { value: "vantage", text: "Vantage" },
    { value: "rapide", text: "Rapide" },
    { value: "valkyrie", text: "Valkyrie" },
    { value: "virage", text: "Virage" },
    { value: "one77", text: "One-77" },
    { value: "lagonda", text: "Lagonda" },
    { value: "cygnet", text: "Cygnet" },
  ],
  audi: [
    {
      value: "make",
      text: "Choose model",
      hidden: true,
    },
    { value: "a1", text: "A1" },
    { value: "a2", text: "A2" },
    { value: "a3", text: "A3" },
    { value: "a4", text: "A4" },
    { value: "a5", text: "A5" },
    { value: "a6", text: "A6" },
    { value: "a7", text: "A7" },
    { value: "a8", text: "A8" },
    { value: "q2", text: "Q2" },
    { value: "q3", text: "Q3" },
    { value: "q4", text: "Q4" },
    { value: "q5", text: "Q5" },
    { value: "q6", text: "Q6" },
    { value: "q7", text: "Q7" },
    { value: "q8", text: "Q8" },
    { value: "r8", text: "R8" },
    { value: "etron", text: "e-tron" },
    { value: "etronGT", text: "e-tron GT" },
    { value: "s3", text: "S3" },
    { value: "s4", text: "S4" },
    { value: "s5", text: "S5" },
    { value: "s6", text: "S6" },
    { value: "s7", text: "S7" },
    { value: "s8", text: "S8" },
    { value: "tt", text: "TT" },
  ],
  bmw: [
    {
      value: "make",
      text: "Choose model",
      hidden: true,
    },
    { value: "1series", text: "1 Series" },
    { value: "2series", text: "2 Series" },
    { value: "3series", text: "3 Series" },
    { value: "4series", text: "4 Series" },
    { value: "5series", text: "5 Series" },
    { value: "6series", text: "6 Series" },
    { value: "7series", text: "7 Series" },
    { value: "8series", text: "8 Series" },
    { value: "i3", text: "i3" },
    { value: "i8", text: "i8" },
    { value: "m2", text: "M2" },
    { value: "m3", text: "M3" },
    { value: "m4", text: "M4" },
    { value: "m5", text: "M5" },
    { value: "m6", text: "M6" },
    { value: "x1", text: "X1" },
    { value: "x2", text: "X2" },
    { value: "x3", text: "X3" },
    { value: "x4", text: "X4" },
    { value: "x5", text: "X5" },
    { value: "x6", text: "X6" },
    { value: "x7", text: "X7" },
    { value: "x8", text: "X8" },
    { value: "z3", text: "Z3" },
    { value: "z4", text: "Z4" },
    { value: "z8", text: "Z8" },
  ],
  bentley: [
    {
      value: "make",
      text: "Choose model",
      hidden: true,
    },
    { value: "arnage", text: "Arnage" },
    { value: "azure", text: "Azure" },
    { value: "bentayga", text: "Bentayga" },
    { value: "brooklands", text: "Brooklands" },
    { value: "continentalFlyingSpur", text: "Continental Flying Spur" },
    { value: "continentalGT", text: "Continental GT" },
    { value: "continentalSupersports", text: "Continental Supersports" },
    { value: "mulsanne", text: "Mulsanne" },
  ],
  bugatti: [
    {
      value: "make",
      text: "Choose model",
      hidden: true,
    },
    { value: "centodieci", text: "Centodieci" },
    { value: "chiron", text: "Chiron" },
    { value: "divo", text: "Divo" },
    { value: "eb110", text: "EB110" },
    { value: "veyron", text: "Veyron" },
  ],
  buick: [
    {
      value: "make",
      text: "Choose model",
      hidden: true,
    },
    { value: "century", text: "Century" },
    { value: "electra", text: "Electra" },
    { value: "enclave", text: "Enclave" },
    { value: "encore", text: "Encore" },
    { value: "encoreGX", text: "Encore GX" },
    { value: "envision", text: "Envision" },
    { value: "lacrosse", text: "LaCrosse" },
    { value: "lesabre", text: "LeSabre" },
    { value: "lucerne", text: "Lucerne" },
    { value: "parkAvenue", text: "Park Avenue" },
    { value: "rainier", text: "Rainier" },
    { value: "reatta", text: "Reatta" },
    { value: "regal", text: "Regal" },
    { value: "rendezvous", text: "Rendezvous" },
    { value: "riviera", text: "Riviera" },
    { value: "skylark", text: "Skylark" },
    { value: "terraza", text: "Terraza" },
    { value: "verano", text: "Verano" },
  ],
  cadillac: [
    {
      value: "make",
      text: "Choose model",
      hidden: true,
    },
    { value: "ats", text: "ATS" },
    { value: "atsV", text: "ATS-V" },
    { value: "ct4", text: "CT4" },
    { value: "ct5", text: "CT5" },
    { value: "ct6", text: "CT6" },
    { value: "cts", text: "CTS" },
    { value: "ctsV", text: "CTS-V" },
    { value: "escalade", text: "Escalade" },
    { value: "escaladeESV", text: "Escalade ESV" },
    { value: "seville", text: "Seville" },
    { value: "srx", text: "SRX" },
    { value: "sts", text: "STS" },
    { value: "xt4", text: "XT4" },
    { value: "xt5", text: "XT5" },
    { value: "xt6", text: "XT6" },
    { value: "xts", text: "XTS" },
  ],
  chevrolet: [
    {
      value: "make",
      text: "Choose model",
      hidden: true,
    },
    { value: "astro", text: "Astro" },
    { value: "avalanche", text: "Avalanche" },
    { value: "aveo", text: "Aveo" },
    { value: "belAir", text: "Bel Air" },
    { value: "beretta", text: "Beretta" },
    { value: "blazer", text: "Blazer" },
    { value: "boltEV", text: "Bolt EV" },
    { value: "camaro", text: "Camaro" },
    { value: "caprice", text: "Caprice" },
    { value: "captivaSport", text: "Captiva Sport" },
    { value: "cavalier", text: "Cavalier" },
    { value: "celebrity", text: "Celebrity" },
    { value: "chevelle", text: "Chevelle" },
    { value: "chevette", text: "Chevette" },
    { value: "citation", text: "Citation" },
    { value: "cityExpress", text: "City Express" },
    { value: "classic", text: "Classic" },
    { value: "cobalt", text: "Cobalt" },
    { value: "colorado", text: "Colorado" },
    { value: "corvette", text: "Corvette" },
    { value: "cruze", text: "Cruze" },
    { value: "elCamino", text: "El Camino" },
    { value: "equinox", text: "Equinox" },
    { value: "express", text: "Express" },
    { value: "gseries", text: "G-Series" },
    { value: "hhr", text: "HHR" },
    { value: "impala", text: "Impala" },
    { value: "kodiak", text: "Kodiak" },
    { value: "lumina", text: "Lumina" },
    { value: "malibu", text: "Malibu" },
    { value: "malibuMaxx", text: "Malibu Maxx" },
    { value: "metro", text: "Metro" },
    { value: "monteCarlo", text: "Monte Carlo" },
    { value: "nova", text: "Nova" },
    { value: "prizm", text: "Prizm" },
    { value: "s10", text: "S10" },
    { value: "silverado", text: "Silverado" },
    { value: "sonic", text: "Sonic" },
    { value: "spark", text: "Spark" },
    { value: "ss", text: "SS" },
    { value: "ssr", text: "SSR" },
    { value: "suburban", text: "Suburban" },
    { value: "tahoe", text: "Tahoe" },
    { value: "tracker", text: "Tracker" },
    { value: "trailblazer", text: "Trailblazer" },
    { value: "traverse", text: "Traverse" },
    { value: "trax", text: "Trax" },
    { value: "uplander", text: "Uplander" },
    { value: "venture", text: "Venture" },
    { value: "volt", text: "Volt" },
  ],
  chrysler: [
    {
      value: "make",
      text: "Choose model",
      hidden: true,
    },
    { value: "200", text: "200" },
    { value: "300", text: "300" },
    { value: "300M", text: "300M" },
    { value: "aspen", text: "Aspen" },
    { value: "concorde", text: "Concorde" },
    { value: "cordoba", text: "Cordoba" },
    { value: "crossfire", text: "Crossfire" },
    { value: "fifthAvenue", text: "Fifth Avenue" },
    { value: "imperial", text: "Imperial" },
    { value: "lhs", text: "LHS" },
    { value: "newYorker", text: "New Yorker" },
    { value: "pacificaN", text: "Pacifica (N)" },
    { value: "pacificaN", text: "Pacifica (N)" },
    { value: "prowler", text: "Prowler" },
    { value: "ptCruiser", text: "PT Cruiser" },
    { value: "sebring", text: "Sebring" },
    { value: "tc", text: "TC" },
    { value: "townAndCountry", text: "Town & Country" },
    { value: "voyager", text: "Voyager" },
  ],
  dodge: [
    {
      value: "make",
      text: "Choose model",
      hidden: true,
    },
    { value: "avenger", text: "Avenger" },
    { value: "caliber", text: "Caliber" },
    { value: "caravan", text: "Caravan" },
    { value: "challenger", text: "Challenger" },
    { value: "charger", text: "Charger" },
    { value: "colt", text: "Colt" },
    { value: "dakota", text: "Dakota" },
    { value: "dart", text: "Dart" },
    { value: "daytona", text: "Daytona" },
    { value: "demon", text: "Demon" },
    { value: "durango", text: "Durango" },
    { value: "grandCaravan", text: "Grand Caravan" },
    { value: "intrepid", text: "Intrepid" },
    { value: "journey", text: "Journey" },
    { value: "magnum", text: "Magnum" },
    { value: "neon", text: "Neon" },
    { value: "nitro", text: "Nitro" },
    { value: "omni", text: "Omni" },
    { value: "ram", text: "Ram" },
    { value: "ramVan", text: "Ram Van" },
    { value: "ramWagon", text: "Ram Wagon" },
    { value: "shadow", text: "Shadow" },
    { value: "spirit", text: "Spirit" },
    { value: "sprinter", text: "Sprinter" },
    { value: "stealth", text: "Stealth" },
    { value: "stratus", text: "Stratus" },
    { value: "viper", text: "Viper" },
  ],

  fiat: [
    {
      value: "make",
      text: "Choose model",
      hidden: true,
    },
    { value: "124Spider", text: "124 Spider" },
    { value: "500", text: "500" },
    { value: "500L", text: "500L" },
    { value: "500X", text: "500X" },
    { value: "barchetta", text: "Barchetta" },
    { value: "brava", text: "Brava" },
    { value: "bravo", text: "Bravo" },
    { value: "cinquecento", text: "Cinquecento" },
    { value: "coupe", text: "Coupe" },
    { value: "croma", text: "Croma" },
    { value: "doblo", text: "Doblo" },
    { value: "ducato", text: "Ducato" },
    { value: "fiorino", text: "Fiorino" },
    { value: "freemont", text: "Freemont" },
    { value: "idea", text: "Idea" },
    { value: "marea", text: "Marea" },
    { value: "multipla", text: "Multipla" },
    { value: "palio", text: "Palio" },
    { value: "panda", text: "Panda" },
    { value: "punto", text: "Punto" },
    { value: "qubo", text: "Qubo" },
    { value: "scudo", text: "Scudo" },
    { value: "sedici", text: "Sedici" },
    { value: "seicento", text: "Seicento" },
    { value: "stilo", text: "Stilo" },
    { value: "talento", text: "Talento" },
    { value: "tipo", text: "Tipo" },
    { value: "ulysse", text: "Ulysse" },
    { value: "uno", text: "Uno" },
    { value: "x1-9", text: "X1/9" },
  ],
  ferrari: [
    {
      value: "make",
      text: "Choose model",
      hidden: true,
    },
    { value: "250GT", text: "250 GT" },
    { value: "288GTO", text: "288 GTO" },
    { value: "308GTB", text: "308 GTB" },
    { value: "308GTS", text: "308 GTS" },
    { value: "328GTB", text: "328 GTB" },
    { value: "328GTS", text: "328 GTS" },
    { value: "348", text: "348" },
    { value: "348Spider", text: "348 Spider" },
    { value: "348TB", text: "348 TB" },
    { value: "348TS", text: "348 TS" },
    { value: "360", text: "360" },
    { value: "360Spider", text: "360 Spider" },
    { value: "456GT", text: "456 GT" },
    { value: "456MGT", text: "456M GT" },
    { value: "458Italia", text: "458 Italia" },
    { value: "458Spider", text: "458 Spider" },
    { value: "488GTB", text: "488 GTB" },
    { value: "488Spider", text: "488 Spider" },
    { value: "512TR", text: "512 TR" },
    { value: "550Maranello", text: "550 Maranello" },
    { value: "575M", text: "575M" },
    { value: "599GTB", text: "599 GTB" },
    { value: "599GTO", text: "599 GTO" },
    { value: "612Scaglietti", text: "612 Scaglietti" },
    { value: "812Superfast", text: "812 Superfast" },
    { value: "california", text: "California" },
    { value: "californiaT", text: "California T" },
    { value: "daytona", text: "Daytona" },
    { value: "enzo", text: "Enzo" },
    { value: "f12berlinetta", text: "F12berlinetta" },
    { value: "f355", text: "F355" },
    { value: "f40", text: "F40" },
    { value: "f430", text: "F430" },
    { value: "f50", text: "F50" },
    { value: "f512m", text: "F512M" },
    { value: "f8tributo", text: "F8 Tributo" },
    { value: "f8spider", text: "F8 Spider" },
    { value: "ff", text: "FF" },
    { value: "gto", text: "GTO" },
    { value: "laFerrari", text: "LaFerrari" },
    { value: "mondial", text: "Mondial" },
    { value: "portofino", text: "Portofino" },
    { value: "testarossa", text: "Testarossa" },
  ],
  ford: [
    {
      value: "make",
      text: "Choose model",
      hidden: true,
    },
    { value: "aerostar", text: "Aerostar" },
    { value: "aspire", text: "Aspire" },
    { value: "bronco", text: "Bronco" },
    { value: "broncoSport", text: "Bronco Sport" },
    { value: "cmax", text: "C-Max" },
    { value: "contour", text: "Contour" },
    { value: "crownVictoria", text: "Crown Victoria" },
    { value: "econoline", text: "Econoline" },
    { value: "ecosport", text: "EcoSport" },
    { value: "edge", text: "Edge" },
    { value: "escape", text: "Escape" },
    { value: "escort", text: "Escort" },
    { value: "excursion", text: "Excursion" },
    { value: "expedition", text: "Expedition" },
    { value: "explorer", text: "Explorer" },
    { value: "f100", text: "F-100" },
    { value: "f150", text: "F-150" },
    { value: "f250", text: "F-250" },
    { value: "f350", text: "F-350" },
    { value: "f450", text: "F-450" },
    { value: "f550", text: "F-550" },
    { value: "fairlane", text: "Fairlane" },
    { value: "falcon", text: "Falcon" },
    { value: "festiva", text: "Festiva" },
    { value: "fiesta", text: "Fiesta" },
    { value: "fiveHundred", text: "Five Hundred" },
    { value: "flex", text: "Flex" },
    { value: "focus", text: "Focus" },
    { value: "freestar", text: "Freestar" },
    { value: "freestyle", text: "Freestyle" },
    { value: "fusion", text: "Fusion" },
    { value: "fusionEnergi", text: "Fusion Energi" },
    { value: "fusionHybrid", text: "Fusion Hybrid" },
    { value: "galaxie", text: "Galaxie" },
    { value: "granada", text: "Granada" },
    { value: "gt", text: "GT" },
    { value: "ltd", text: "LTD" },
    { value: "maverick", text: "Maverick" },
    { value: "modelA", text: "Model A" },
    { value: "modelT", text: "Model T" },
    { value: "mustang", text: "Mustang" },
    { value: "pinto", text: "Pinto" },
    { value: "probe", text: "Probe" },
    { value: "ranchero", text: "Ranchero" },
    { value: "ranger", text: "Ranger" },
    { value: "taunus", text: "Taunus" },
    { value: "taurus", text: "Taurus" },
    { value: "thunderbird", text: "Thunderbird" },
    { value: "torino", text: "Torino" },
    { value: "transit", text: "Transit" },
    { value: "transitConnect", text: "Transit Connect" },
    { value: "windstar", text: "Windstar" },
  ],
  genesis: [
    {
      value: "make",
      text: "Choose model",
      hidden: true,
    },
    { value: "g70", text: "G70" },
    { value: "g80", text: "G80" },
    { value: "g90", text: "G90" },
    { value: "gv70", text: "GV70" },
    { value: "gv80", text: "GV80" },
    { value: "gv90", text: "GV90" },
  ],
  gmc: [
    {
      value: "make",
      text: "Choose model",
      hidden: true,
    },
    { value: "acadia", text: "Acadia" },
    { value: "canyon", text: "Canyon" },
    { value: "envoy", text: "Envoy" },
    { value: "envoyXL", text: "Envoy XL" },
    { value: "envoyXUV", text: "Envoy XUV" },
    { value: "jimmy", text: "Jimmy" },
    { value: "rallyWagon", text: "Rally Wagon" },
    { value: "safari", text: "Safari" },
    { value: "savana", text: "Savana" },
    { value: "sierra", text: "Sierra" },
    { value: "sierra1500", text: "Sierra 1500" },
    { value: "sierra2500HD", text: "Sierra 2500HD" },
    { value: "sierra3500", text: "Sierra 3500" },
    { value: "sierra3500HD", text: "Sierra 3500HD" },
    { value: "terrain", text: "Terrain" },
    { value: "typhoon", text: "Typhoon" },
    { value: "yukon", text: "Yukon" },
    { value: "yukonXL", text: "Yukon XL" },
  ],
  honda: [
    {
      value: "make",
      text: "Choose model",
      hidden: true,
    },
    { value: "accord", text: "Accord" },
    { value: "civic", text: "Civic" },
    { value: "clarity", text: "Clarity" },
    { value: "crv", text: "CR-V" },
    { value: "crz", text: "CR-Z" },
    { value: "element", text: "Element" },
    { value: "fit", text: "Fit" },
    { value: "hrv", text: "HR-V" },
    { value: "insight", text: "Insight" },
    { value: "odyssey", text: "Odyssey" },
    { value: "passport", text: "Passport" },
    { value: "pilot", text: "Pilot" },
    { value: "prelude", text: "Prelude" },
    { value: "ridgeline", text: "Ridgeline" },
    { value: "s2000", text: "S2000" },
    { value: "stepwgn", text: "Stepwgn" },
    { value: "vamos", text: "Vamos" },
  ],
  hummer: [
    {
      value: "make",
      text: "Choose model",
      hidden: true,
    },
    { value: "h1", text: "H1" },
    { value: "h2", text: "H2" },
    { value: "h3", text: "H3" },
  ],
  hyundai: [
    {
      value: "make",
      text: "Choose model",
      hidden: true,
    },
    { value: "accent", text: "Accent" },
    { value: "atostar", text: "Atos Prime" },
    { value: "azera", text: "Azera" },
    { value: "elantra", text: "Elantra" },
    { value: "entourage", text: "Entourage" },
    { value: "equus", text: "Equus" },
    { value: "genesis", text: "Genesis" },
    { value: "genesisCoupe", text: "Genesis Coupe" },
    { value: "getz", text: "Getz" },
    { value: "grandeur", text: "Grandeur" },
    { value: "h1", text: "H-1" },
    { value: "ioniq", text: "Ioniq" },
    { value: "ix20", text: "ix20" },
    { value: "ix35", text: "ix35" },
    { value: "kona", text: "Kona" },
    { value: "lantra", text: "Lantra" },
    { value: "lavita", text: "Lavita" },
    { value: "matrix", text: "Matrix" },
    { value: "n2025", text: "N 2025" },
    { value: "nexo", text: "Nexo" },
    { value: "pavise", text: "Pavise" },
    { value: "santaFe", text: "Santa Fe" },
    { value: "sonata", text: "Sonata" },
    { value: "sonica", text: "Sonica" },
    { value: "tucson", text: "Tucson" },
    { value: "veloster", text: "Veloster" },
    { value: "venue", text: "Venue" },
    { value: "veracruz", text: "Veracruz" },
    { value: "volester", text: "Volester" },
    { value: "xcent", text: "Xcent" },
  ],
  infiniti: [
    {
      value: "make",
      text: "Choose model",
      hidden: true,
    },
    { value: "ex", text: "EX" },
    { value: "fx", text: "FX" },
    { value: "g", text: "G" },
    { value: "i30", text: "i30" },
    { value: "j30", text: "J30" },
    { value: "m", text: "M" },
    { value: "q30", text: "Q30" },
    { value: "q45", text: "Q45" },
    { value: "q50", text: "Q50" },
    { value: "q60", text: "Q60" },
    { value: "q70", text: "Q70" },
    { value: "qx30", text: "QX30" },
    { value: "qx4", text: "QX4" },
    { value: "qx50", text: "QX50" },
    { value: "qx56", text: "QX56" },
    { value: "qx60", text: "QX60" },
    { value: "qx70", text: "QX70" },
    { value: "qx80", text: "QX80" },
  ],
  isuzu: [
    {
      value: "make",
      text: "Choose model",
      hidden: true,
    },
    { value: "amigo", text: "Amigo" },
    { value: "ascender", text: "Ascender" },
    { value: "axiom", text: "Axiom" },
    { value: "gemini", text: "Gemini" },
    { value: "hombre", text: "Hombre" },
    { value: "iMark", text: "i-Mark" },
    { value: "impulse", text: "Impulse" },
    { value: "mu", text: "MU" },
    { value: "npr", text: "NPR" },
    { value: "nqr", text: "NQR" },
    { value: "odeyssey", text: "Odeyssey" },
    { value: "pickup", text: "Pickup" },
    { value: "rodeo", text: "Rodeo" },
    { value: "stylus", text: "Stylus" },
    { value: "trooper", text: "Trooper" },
    { value: "vehicross", text: "VehiCROSS" },
  ],
  jaguar: [
    {
      value: "make",
      text: "Choose model",
      hidden: true,
    },
    { value: "420", text: "420" },
    { value: "ePace", text: "E-Pace" },
    { value: "fpace", text: "F-Pace" },
    { value: "ftype", text: "F-Type" },
    { value: "sType", text: "S-Type" },
    { value: "xType", text: "X-Type" },
    { value: "xe", text: "XE" },
    { value: "xf", text: "XF" },
    { value: "xj", text: "XJ" },
    { value: "xj12", text: "XJ12" },
    { value: "xj6", text: "XJ6" },
    { value: "xj8", text: "XJ8" },
    { value: "xjr", text: "XJR" },
    { value: "xjs", text: "XJS" },
    { value: "xk", text: "XK" },
    { value: "xk8", text: "XK8" },
    { value: "xkr", text: "XKR" },
    { value: "xkss", text: "XKSS" },
  ],
  jeep: [
    {
      value: "make",
      text: "Choose model",
      hidden: true,
    },
    { value: "cherokee", text: "Cherokee" },
    { value: "cj", text: "CJ" },
    { value: "comanche", text: "Comanche" },
    { value: "commander", text: "Commander" },
    { value: "compass", text: "Compass" },
    { value: "gladiator", text: "Gladiator" },
    { value: "grandCherokee", text: "Grand Cherokee" },
    { value: "grandWagoneer", text: "Grand Wagoneer" },
    { value: "liberty", text: "Liberty" },
    { value: "patriot", text: "Patriot" },
    { value: "renegade", text: "Renegade" },
    { value: "scrambler", text: "Scrambler" },
    { value: "wagoneer", text: "Wagoneer" },
    { value: "wrangler", text: "Wrangler" },
  ],
  kia: [
    {
      value: "make",
      text: "Choose model",
      hidden: true,
    },
    { value: "amanti", text: "Amanti" },
    { value: "besta", text: "Besta" },
    { value: "borrego", text: "Borrego" },
    { value: "cadenza", text: "Cadenza" },
    { value: "carens", text: "Carens" },
    { value: "carnival", text: "Carnival" },
    { value: "ceed", text: "Ceed" },
    { value: "cerato", text: "Cerato" },
    { value: "clarus", text: "Clarus" },
    { value: "enterprise", text: "Enterprise" },
    { value: "forte", text: "Forte" },
    { value: "joice", text: "Joice" },
    { value: "k2700", text: "K2700" },
    { value: "k2900", text: "K2900" },
    { value: "k900", text: "K900" },
    { value: "magentis", text: "Magentis" },
    { value: "mentor", text: "Mentor" },
    { value: "mohave", text: "Mohave" },
    { value: "niro", text: "Niro" },
    { value: "olet", text: "Olet" },
    { value: "optima", text: "Optima" },
    { value: "optimaHybrid", text: "Optima Hybrid" },
    { value: "optimaPhev", text: "Optima PHEV" },
    { value: "picanto", text: "Picanto" },
    { value: "potentia", text: "Potentia" },
    { value: "pregio", text: "Pregio" },
    { value: "pride", text: "Pride" },
    { value: "proCeed", text: "ProCeed" },
    { value: "quoris", text: "Quoris" },
    { value: "retona", text: "Retona" },
    { value: "rio", text: "Rio" },
    { value: "roadster", text: "Roadster" },
    { value: "sedona", text: "Sedona" },
    { value: "sephia", text: "Sephia" },
    { value: "shuma", text: "Shuma" },
    { value: "sorento", text: "Sorento" },
    { value: "soul", text: "Soul" },
    { value: "spectra", text: "Spectra" },
    { value: "sportage", text: "Sportage" },
    { value: "stonic", text: "Stonic" },
    { value: "telluride", text: "Telluride" },
    { value: "venga", text: "Venga" },
  ],
  lamborghini: [
    {
      value: "make",
      text: "Choose model",
      hidden: true,
    },
    { value: "aventador", text: "Aventador" },
    { value: "countach", text: "Countach" },
    { value: "diablo", text: "Diablo" },
    { value: "gallardo", text: "Gallardo" },
    { value: "huracan", text: "Huracan" },
    { value: "jalpa", text: "Jalpa" },
    { value: "lm", text: "LM" },
    { value: "murcielago", text: "Murcielago" },
    { value: "sestoElemento", text: "Sesto Elemento" },
    { value: "urus", text: "Urus" },
  ],
  lancia: [
    {
      value: "make",
      text: "Choose model",
      hidden: true,
    },
    { value: "appla", text: "Appla" },
    { value: "beta", text: "Beta" },
    { value: "dedra", text: "Dedra" },
    { value: "flaminia", text: "Flaminia" },
    { value: "flavia", text: "Flavia" },
    { value: "fulvia", text: "Fulvia" },
    { value: "gamma", text: "Gamma" },
    { value: "kappa", text: "Kappa" },
    { value: "lybra", text: "Lybra" },
    { value: "montecarlo", text: "Montecarlo" },
    { value: "musa", text: "Musa" },
    { value: "phedra", text: "Phedra" },
    { value: "prisma", text: "Prisma" },
    { value: "stratos", text: "Stratos" },
    { value: "them", text: "Them" },
    { value: "thesis", text: "Thesis" },
    { value: "voyager", text: "Voyager" },
    { value: "y", text: "Y" },
    { value: "ypsilon", text: "Ypsilon" },
    { value: "zeta", text: "Zeta" },
  ],
  landRover: [
    {
      value: "make",
      text: "Choose model",
      hidden: true,
    },
    { value: "defender", text: "Defender" },
    { value: "discovery", text: "Discovery" },
    { value: "discoverySport", text: "Discovery Sport" },
    { value: "freelander", text: "Freelander" },
    { value: "lr2", text: "LR2" },
    { value: "lr3", text: "LR3" },
    { value: "lr4", text: "LR4" },
    { value: "rangeRover", text: "Range Rover" },
    { value: "rangeRoverEvoque", text: "Range Rover Evoque" },
    { value: "rangeRoverSport", text: "Range Rover Sport" },
    { value: "rangeRoverVelar", text: "Range Rover Velar" },
  ],
  lexus: [
    {
      value: "make",
      text: "Choose model",
      hidden: true,
    },
    { value: "ct", text: "CT" },
    { value: "es", text: "ES" },
    { value: "gs", text: "GS" },
    { value: "gx", text: "GX" },
    { value: "hs", text: "HS" },
    { value: "is", text: "IS" },
    { value: "lc", text: "LC" },
    { value: "lfa", text: "LFA" },
    { value: "ls", text: "LS" },
    { value: "lx", text: "LX" },
    { value: "nx", text: "NX" },
    { value: "rc", text: "RC" },
    { value: "rx", text: "RX" },
    { value: "sc", text: "SC" },
    { value: "ux", text: "UX" },
  ],
  lincoln: [
    {
      value: "make",
      text: "Choose model",
      hidden: true,
    },
    { value: "aviator", text: "Aviator" },
    { value: "blackwood", text: "Blackwood" },
    { value: "continental", text: "Continental" },
    { value: "corsair", text: "Corsair" },
    { value: "ls", text: "LS" },
    { value: "marklt", text: "Mark LT" },
    { value: "markvi", text: "Mark VI" },
    { value: "markviii", text: "Mark VIII" },
    { value: "mkc", text: "MKC" },
    { value: "mks", text: "MKS" },
    { value: "mkt", text: "MKT" },
    { value: "mkx", text: "MKX" },
    { value: "mkz", text: "MKZ" },
    { value: "navigator", text: "Navigator" },
    { value: "townCar", text: "Town Car" },
    { value: "zephyr", text: "Zephyr" },
  ],
  lotus: [
    {
      value: "make",
      text: "Choose model",
      hidden: true,
    },
    { value: "elise", text: "Elise" },
    { value: "elite", text: "Elite" },
    { value: "emerson", text: "Emerson" },
    { value: "esprit", text: "Esprit" },
    { value: "europe", text: "Europe" },
    { value: "evija", text: "Evija" },
    { value: "exige", text: "Exige" },
    { value: "seven", text: "Seven" },
    { value: "superSeven", text: "Super Seven" },
    { value: "twenty", text: "Twenty" },
  ],
  maserati: [
    {
      value: "make",
      text: "Choose model",
      hidden: true,
    },
    { value: "3200gt", text: "3200 GT" },
    { value: "4200", text: "4200" },
    { value: "alfieri", text: "Alfieri" },
    { value: "biturbo", text: "Biturbo" },
    { value: "bora", text: "Bora" },
    { value: "ghibli", text: "Ghibli" },
    { value: "granCabrio", text: "GranCabrio" },
    { value: "granSport", text: "GranSport" },
    { value: "granTurismo", text: "GranTurismo" },
    { value: "indy", text: "Indy" },
    { value: "karif", text: "Karif" },
    { value: "kubang", text: "Kubang" },
    { value: "mc12", text: "MC12" },
    { value: "merak", text: "Merak" },
    { value: "quattroporte", text: "Quattroporte" },
    { value: "royale", text: "Royale" },
    { value: "spyder", text: "Spyder" },
  ],
  maybach: [
    {
      value: "make",
      text: "Choose model",
      hidden: true,
    },
    { value: "57", text: "57" },
    { value: "62", text: "62" },
    { value: "maybach", text: "Maybach" },
  ],
  mazda: [
    {
      value: "make",
      text: "Choose model",
      hidden: true,
    },
    { value: "121", text: "121" },
    { value: "2", text: "2" },
    { value: "3", text: "3" },
    { value: "323", text: "323" },
    { value: "5", text: "5" },
    { value: "6", text: "6" },
    { value: "616", text: "616" },
    { value: "626", text: "626" },
    { value: "818", text: "818" },
    { value: "929", text: "929" },
    { value: "bSeries", text: "B-Series" },
    { value: "cosmo", text: "Cosmo" },
    { value: "cx3", text: "CX-3" },
    { value: "cx30", text: "CX-30" },
    { value: "cx5", text: "CX-5" },
    { value: "cx7", text: "CX-7" },
    { value: "cx8", text: "CX-8" },
    { value: "cx9", text: "CX-9" },
    { value: "glc", text: "GLC" },
    { value: "laputa", text: "Laputa" },
    { value: "mPV", text: "MPV" },
    { value: "mX3", text: "MX-3" },
    { value: "mX30", text: "MX-30" },
    { value: "mX5", text: "MX-5" },
    { value: "mX6", text: "MX-6" },
    { value: "miata", text: "Miata" },
    { value: "millenia", text: "Millenia" },
    { value: "mpv", text: "MPV" },
    { value: "mx3", text: "MX-3" },
    { value: "mx5", text: "MX-5" },
    { value: "mx6", text: "MX-6" },
    { value: "premacy", text: "Premacy" },
    { value: "protege", text: "Protege" },
    { value: "r100", text: "R-100" },
    { value: "r130", text: "R-130" },
    { value: "r360Coupe", text: "R360 Coupe" },
    { value: "rX3", text: "RX-3" },
    { value: "rX4", text: "RX-4" },
    { value: "rX7", text: "RX-7" },
    { value: "rX8", text: "RX-8" },
    { value: "tribute", text: "Tribute" },
    { value: "verisa", text: "Verisa" },
    { value: "xedos6", text: "Xedos 6" },
    { value: "xedos9", text: "Xedos 9" },
  ],
  mclaren: [
    {
      value: "make",
      text: "Choose model",
      hidden: true,
    },
    { value: "540c", text: "540C" },
    { value: "570gt", text: "570GT" },
    { value: "570s", text: "570S" },
    { value: "600lt", text: "600LT" },
    { value: "625c", text: "625C" },
    { value: "650s", text: "650S" },
    { value: "675lt", text: "675LT" },
    { value: "720s", text: "720S" },
    { value: "f1", text: "F1" },
    { value: "gt", text: "GT" },
    { value: "m6gt", text: "M6GT" },
    { value: "mp412c", text: "MP4-12C" },
    { value: "p1", text: "P1" },
    { value: "senna", text: "Senna" },
  ],
  mercedesBenz: [
    {
      value: "make",
      text: "Choose model",
      hidden: true,
    },
    { value: "aClass", text: "A-Class" },
    { value: "amgGt", text: "AMG GT" },
    { value: "bClass", text: "B-Class" },
    { value: "cClass", text: "C-Class" },
    { value: "cLassCls", text: "CLass CLS" },
    { value: "cLassClsShootingBrake", text: "CLass CLS Shooting Brake" },
    { value: "cLassEqc", text: "CLass EQC" },
    { value: "cLassGlcCoupe", text: "CLass GLC Coupe" },
    { value: "cLassGleCoupe", text: "CLass GLE Coupe" },
    { value: "cLassGls", text: "CLass GLS" },
    { value: "eClass", text: "E-Class" },
    { value: "gClass", text: "G-Class" },
    { value: "gLa", text: "GLA" },
    { value: "gLaClass", text: "GLA-Class" },
    { value: "gLe", text: "GLE" },
    { value: "gLeClass", text: "GLE-Class" },
    { value: "gLf", text: "GLF" },
    { value: "gLkClass", text: "GLK-Class" },
    { value: "gLs", text: "GLS" },
    { value: "gLsClass", text: "GLS-Class" },
    { value: "mClass", text: "M-Class" },
    { value: "maybachSClass", text: "Maybach S-Class" },
    { value: "mLClass", text: "ML-Class" },
    { value: "metris", text: "Metris" },
    { value: "rClass", text: "R-Class" },
    { value: "sClass", text: "S-Class" },
    { value: "sLClass", text: "SL-Class" },
    { value: "sLc", text: "SLC" },
    { value: "sLkClass", text: "SLK-Class" },
    { value: "sLsAmgClass", text: "SLS AMG-Class" },
    { value: "sLsClass", text: "SLS-Class" },
    { value: "sprinter", text: "Sprinter" },
    { value: "viano", text: "Viano" },
    { value: "vito", text: "Vito" },
  ],
  mercury: [
    {
      value: "make",
      text: "Choose model",
      hidden: true,
    },
    { value: "capri", text: "Capri" },
    { value: "comet", text: "Comet" },
    { value: "cougar", text: "Cougar" },
    { value: "grandMarquis", text: "Grand Marquis" },
    { value: "lynx", text: "Lynx" },
    { value: "marauder", text: "Marauder" },
    { value: "mariner", text: "Mariner" },
    { value: "marquis", text: "Marquis" },
    { value: "milan", text: "Milan" },
    { value: "montclair", text: "Montclair" },
    { value: "monterey", text: "Monterey" },
    { value: "mountaineer", text: "Mountaineer" },
    { value: "mystique", text: "Mystique" },
    { value: "parkLane", text: "Park Lane" },
    { value: "sable", text: "Sable" },
    { value: "topaz", text: "Topaz" },
    { value: "tracer", text: "Tracer" },
    { value: "villager", text: "Villager" },
  ],
  mini: [
    {
      value: "make",
      text: "Choose model",
      hidden: true,
    },
    { value: "clubman", text: "Clubman" },
    { value: "cooper", text: "Cooper" },
    { value: "cooperCountryman", text: "Cooper Countryman" },
    { value: "cooperCoupe", text: "Cooper Coupe" },
    { value: "cooperPaceman", text: "Cooper Paceman" },
    { value: "cooperRoadster", text: "Cooper Roadster" },
    { value: "cooperS", text: "Cooper S" },
    { value: "cooperSCountryman", text: "Cooper S Countryman" },
    { value: "cooperSCoupe", text: "Cooper S Coupe" },
    { value: "cooperSPaceman", text: "Cooper S Paceman" },
    { value: "cooperSRoadster", text: "Cooper S Roadster" },
    { value: "countryman", text: "Countryman" },
    { value: "coupe", text: "Coupe" },
    { value: "paceman", text: "Paceman" },
    { value: "roadster", text: "Roadster" },
  ],
  mitsubishi: [
    {
      value: "make",
      text: "Choose model",
      hidden: true,
    },
    { value: "3000gt", text: "3000GT" },
    { value: "asx", text: "ASX" },
    { value: "carisma", text: "Carisma" },
    { value: "colt", text: "Colt" },
    { value: "cordia", text: "Cordia" },
    { value: "delica", text: "Delica" },
    { value: "diamante", text: "Diamante" },
    { value: "eclipse", text: "Eclipse" },
    { value: "endeavor", text: "Endeavor" },
    { value: "expo", text: "Expo" },
    { value: "galant", text: "Galant" },
    { value: "grandis", text: "Grandis" },
    { value: "iMiev", text: "i-Miev" },
    { value: "l200", text: "L200" },
    { value: "l300", text: "L300" },
    { value: "lancer", text: "Lancer" },
    { value: "montero", text: "Montero" },
    { value: "outlander", text: "Outlander" },
    { value: "pajero", text: "Pajero" },
    { value: "pajeroPinin", text: "Pajero Pinin" },
    { value: "pajeroSport", text: "Pajero Sport" },
    { value: "precis", text: "Precis" },
    { value: "raider", text: "Raider" },
    { value: "rVR", text: "RVR" },
    { value: "shogun", text: "Shogun" },
    { value: "shogunPinin", text: "Shogun Pinin" },
    { value: "sigma", text: "Sigma" },
    { value: "spaceGear", text: "Space Gear" },
    { value: "spaceRunner", text: "Space Runner" },
    { value: "spaceStar", text: "Space Star" },
    { value: "spaceWagon", text: "Space Wagon" },
    { value: "starion", text: "Starion" },
    { value: "tredia", text: "Tredia" },
    { value: "triton", text: "Triton" },
  ],
  nissan: [
    {
      value: "make",
      text: "Choose model",
      hidden: true,
    },
    { value: "100nx", text: "100NX" },
    { value: "200sx", text: "200SX" },
    { value: "240sx", text: "240SX" },
    { value: "280zx", text: "280ZX" },
    { value: "300zx", text: "300ZX" },
    { value: "350z", text: "350Z" },
    { value: "370z", text: "370Z" },
    { value: "almera", text: "Almera" },
    { value: "almeraTino", text: "Almera Tino" },
    { value: "altima", text: "Altima" },
    { value: "armada", text: "Armada" },
    { value: "bluebird", text: "Bluebird" },
    { value: "cedric", text: "Cedric" },
    { value: "cima", text: "Cima" },
    { value: "cube", text: "Cube" },
    { value: "evalia", text: "Evalia" },
    { value: "fairladyZ", text: "Fairlady Z" },
    { value: "frontier", text: "Frontier" },
    { value: "gtR", text: "GT-R" },
    { value: "interstar", text: "Interstar" },
    { value: "juke", text: "Juke" },
    { value: "kicks", text: "Kicks" },
    { value: "kingCab", text: "King Cab" },
    { value: "kubistar", text: "Kubistar" },
    { value: "largo", text: "Largo" },
    { value: "laurel", text: "Laurel" },
    { value: "leaf", text: "Leaf" },
    { value: "maxima", text: "Maxima" },
    { value: "micra", text: "Micra" },
    { value: "murano", text: "Murano" },
    { value: "navara", text: "Navara" },
    { value: "note", text: "Note" },
    { value: "np300", text: "NP300" },
    { value: "nv200", text: "NV200" },
    { value: "nv400", text: "NV400" },
    { value: "pathfinder", text: "Pathfinder" },
    { value: "patrol", text: "Patrol" },
    { value: "pickUp", text: "Pick Up" },
    { value: "pixo", text: "Pixo" },
    { value: "prairie", text: "Prairie" },
    { value: "primastar", text: "Primastar" },
    { value: "primera", text: "Primera" },
    { value: "pulsar", text: "Pulsar" },
    { value: "quest", text: "Quest" },
    { value: "rogue", text: "Rogue" },
    { value: "rogueSelect", text: "Rogue Select" },
    { value: "sentra", text: "Sentra" },
    { value: "silvia", text: "Silvia" },
    { value: "skyline", text: "Skyline" },
    { value: "stanza", text: "Stanza" },
    { value: "sunny", text: "Sunny" },
    { value: "teana", text: "Teana" },
    { value: "terrano", text: "Terrano" },
    { value: "tiida", text: "Tiida" },
    { value: "titan", text: "Titan" },
    { value: "trade", text: "Trade" },
    { value: "ud", text: "UD" },
    { value: "urvan", text: "Urvan" },
    { value: "vanette", text: "Vanette" },
    { value: "versa", text: "Versa" },
    { value: "xterra", text: "Xterra" },
    { value: "z", text: "Z" },
  ],
  noble: [
    {
      value: "make",
      text: "Choose model",
      hidden: true,
    },
    { value: "m10", text: "M10" },
    { value: "m12", text: "M12" },
    { value: "m400", text: "M400" },
    { value: "m600", text: "M600" },
  ],
  opel: [
    {
      value: "make",
      text: "Choose model",
      hidden: true,
    },
    { value: "adam", text: "Adam" },
    { value: "admiral", text: "Admiral" },
    { value: "agila", text: "Agila" },
    { value: "ampera", text: "Ampera" },
    { value: "antara", text: "Antara" },
    { value: "arena", text: "Arena" },
    { value: "ascona", text: "Ascona" },
    { value: "astra", text: "Astra" },
    { value: "calibra", text: "Calibra" },
    { value: "campo", text: "Campo" },
    { value: "cascada", text: "Cascada" },
    { value: "combo", text: "Combo" },
    { value: "commodore", text: "Commodore" },
    { value: "corsa", text: "Corsa" },
    { value: "crosslandX", text: "Crossland X" },
    { value: "frontera", text: "Frontera" },
    { value: "gT", text: "GT" },
    { value: "insignia", text: "Insignia" },
    { value: "kadett", text: "Kadett" },
    { value: "kappa", text: "Kappa" },
    { value: "manta", text: "Manta" },
    { value: "meriva", text: "Meriva" },
    { value: "mokka", text: "Mokka" },
    { value: "monterey", text: "Monterey" },
    { value: "monza", text: "Monza" },
    { value: "movano", text: "Movano" },
    { value: "neMovano", text: "NeMovano" },
    { value: "omega", text: "Omega" },
    { value: "rakE", text: "RakE" },
    { value: "reKord", text: "ReKord" },
    { value: "senator", text: "Senator" },
    { value: "signum", text: "Signum" },
    { value: "sintra", text: "Sintra" },
    { value: "speedster", text: "Speedster" },
    { value: "tigra", text: "Tigra" },
    { value: "tour", text: "Tour" },
    { value: "vectra", text: "Vectra" },
    { value: "vita", text: "Vita" },
    { value: "vivaro", text: "Vivaro" },
    { value: "zafira", text: "Zafira" },
  ],
  pagani: [
    {
      value: "make",
      text: "Choose model",
      hidden: true,
    },
    { value: "huayra", text: "Huayra" },
    { value: "huayraRoadster", text: "Huayra Roadster" },
    { value: "zonda", text: "Zonda" },
    { value: "zondaCinque", text: "Zonda Cinque" },
    { value: "zondaF", text: "Zonda F" },
    { value: "zondaRoadster", text: "Zonda Roadster" },
  ],
  peugeot: [
    {
      value: "make",
      text: "Choose model",
      hidden: true,
    },
    { value: "1007", text: "1007" },
    { value: "104", text: "104" },
    { value: "106", text: "106" },
    { value: "107", text: "107" },
    { value: "108", text: "108" },
    { value: "2008", text: "2008" },
    { value: "204", text: "204" },
    { value: "205", text: "205" },
    { value: "206", text: "206" },
    { value: "207", text: "207" },
    { value: "208", text: "208" },
    { value: "3008", text: "3008" },
    { value: "301", text: "301" },
    { value: "304", text: "304" },
    { value: "305", text: "305" },
    { value: "306", text: "306" },
    { value: "307", text: "307" },
    { value: "308", text: "308" },
    { value: "309", text: "309" },
    { value: "4007", text: "4007" },
    { value: "4008", text: "4008" },
    { value: "403", text: "403" },
    { value: "404", text: "404" },
    { value: "405", text: "405" },
    { value: "406", text: "406" },
    { value: "407", text: "407" },
    { value: "408", text: "408" },
    { value: "5008", text: "5008" },
    { value: "504", text: "504" },
    { value: "505", text: "505" },
    { value: "508", text: "508" },
    { value: "604", text: "604" },
    { value: "605", text: "605" },
    { value: "607", text: "607" },
    { value: "608", text: "608" },
    { value: "806", text: "806" },
    { value: "807", text: "807" },
    { value: "Bipper", text: "Bipper" },
    { value: "expert", text: "Expert" },
    { value: "ion", text: "ION" },
    { value: "ionCUTe", text: "ION CUTE" },
    { value: "partner", text: "Partner" },
    { value: "rcz", text: "RCZ" },
    { value: "rifter", text: "Rifter" },
    { value: "traveller", text: "Traveller" },
  ],
  plymouth: [
    {
      value: "make",
      text: "Choose model",
      hidden: true,
    },
    { value: "acclaim", text: "Acclaim" },
    { value: "barracuda", text: "Barracuda" },
    { value: "belvedere", text: "Belvedere" },
    { value: "breeze", text: "Breeze" },
    { value: "caravelle", text: "Caravelle" },
    { value: "champ", text: "Champ" },
    { value: "cranbrook", text: "Cranbrook" },
    { value: "duster", text: "Duster" },
    { value: "fury", text: "Fury" },
    { value: "gtx", text: "GTX" },
    { value: "horizon", text: "Horizon" },
    { value: "laser", text: "Laser" },
    { value: "neon", text: "Neon" },
    { value: "prowler", text: "Prowler" },
    { value: "reliant", text: "Reliant" },
    { value: "sapporo", text: "Sapporo" },
    { value: "sundance", text: "Sundance" },
    { value: "valiant", text: "Valiant" },
    { value: "volare", text: "Volare" },
    { value: "voyager", text: "Voyager" },
  ],
  pontiac: [
    {
      value: "make",
      text: "Choose model",
      hidden: true,
    },
    { value: "1000", text: "1000" },
    { value: "2000Sunbird", text: "2000 Sunbird" },
    { value: "6000", text: "6000" },
    { value: "aztek", text: "Aztek" },
    { value: "banshee", text: "Banshee" },
    { value: "bonneville", text: "Bonneville" },
    { value: "catalina", text: "Catalina" },
    { value: "fiero", text: "Fiero" },
    { value: "firebird", text: "Firebird" },
    { value: "g3", text: "G3" },
    { value: "g4", text: "G4" },
    { value: "g5", text: "G5" },
    { value: "g6", text: "G6" },
    { value: "g8", text: "G8" },
    { value: "grandAm", text: "Grand Am" },
    { value: "grandPrix", text: "Grand Prix" },
    { value: "gto", text: "GTO" },
    { value: "lemans", text: "LeMans" },
    { value: "montana", text: "Montana" },
    { value: "solstice", text: "Solstice" },
    { value: "sunbird", text: "Sunbird" },
    { value: "sunfire", text: "Sunfire" },
    { value: "torrent", text: "Torrent" },
    { value: "trans", text: "Trans" },
    { value: "vibe", text: "Vibe" },
  ],
  porsche: [
    {
      value: "make",
      text: "Choose model",
      hidden: true,
    },
    { value: "356", text: "356" },
    { value: "718", text: "718" },
    { value: "718Boxster", text: "718 Boxster" },
    { value: "718Cayman", text: "718 Cayman" },
    { value: "804", text: "804" },
    { value: "550", text: "550" },
    { value: "911", text: "911" },
    { value: "911Gt1", text: "911 GT1" },
    { value: "911Gt2", text: "911 GT2" },
    { value: "911Gt3", text: "911 GT3" },
    { value: "911Gt3Rs", text: "911 GT3 RS" },
    { value: "911R", text: "911 R" },
    { value: "911Targa", text: "911 Targa" },
    { value: "914", text: "914" },
    { value: "918", text: "918" },
    { value: "924", text: "924" },
    { value: "928", text: "928" },
    { value: "944", text: "944" },
    { value: "959", text: "959" },
    { value: "968", text: "968" },
    { value: "boxster", text: "Boxster" },
    { value: "carrerGt", text: "Carrer GT" },
    { value: "carreraGt", text: "Carrera GT" },
    { value: "cayenne", text: "Cayenne" },
    { value: "cayman", text: "Cayman" },
    { value: "macan", text: "Macan" },
    { value: "panamera", text: "Panamera" },
  ],
  proton: [
    {
      value: "make",
      text: "Choose model",
      hidden: true,
    },
    { value: "400", text: "400" },
    { value: "ATlIs", text: "ATlIs" },
    { value: "persona", text: "Persona" },
    { value: "saga", text: "Saga" },
    { value: "satria", text: "Satria" },
    { value: "waja", text: "Waja" },
  ],
  ram: [
    {
      value: "make",
      text: "Choose model",
      hidden: true,
    },
    { value: "1500", text: "1500" },
    { value: "2500", text: "2500" },
    { value: "3500", text: "3500" },
    { value: "charger", text: "Charger" },
    { value: "dakota", text: "Dakota" },
    { value: "d150", text: "D150" },
    { value: "d250", text: "D250" },
    { value: "d350", text: "D350" },
    { value: "dart", text: "Dart" },
    { value: "daytona", text: "Daytona" },
    { value: "durango", text: "Durango" },
    { value: "journey", text: "Journey" },
    { value: "magnum", text: "Magnum" },
    { value: "neon", text: "Neon" },
    { value: "nitro", text: "Nitro" },
    { value: "ram", text: "Ram" },
    { value: "ramVan", text: "Ram Van" },
    { value: "stealth", text: "Stealth" },
    { value: "stratus", text: "Stratus" },
    { value: "viper", text: "Viper" },
  ],
  renault: [
    {
      value: "make",
      text: "Choose model",
      hidden: true,
    },
    { value: "11", text: "11" },
    { value: "12", text: "12" },
    { value: "14", text: "14" },
    { value: "15", text: "15" },
    { value: "16", text: "16" },
    { value: "17", text: "17" },
    { value: "18", text: "18" },
    { value: "19", text: "19" },
    { value: "20", text: "20" },
    { value: "21", text: "21" },
    { value: "25", text: "25" },
    { value: "30", text: "30" },
    { value: "4", text: "4" },
    { value: "5", text: "5" },
    { value: "6", text: "6" },
    { value: "9", text: "9" },
    { value: "alaskan", text: "Alaskan" },
    { value: "avantime", text: "Avantime" },
    { value: "captur", text: "Captur" },
    { value: "clio", text: "Clio" },
    { value: "dauphine", text: "Dauphine" },
    { value: "espace", text: "Espace" },
    { value: "floride", text: "Floride" },
    { value: "fluence", text: "Fluence" },
    { value: "fregate", text: "Fregate" },
    { value: "kangoo", text: "Kangoo" },
    { value: "koleos", text: "Koleos" },
    { value: "laguna", text: "Laguna" },
    { value: "latitude", text: "Latitude" },
    { value: "logan", text: "Logan" },
    { value: "master", text: "Master" },
    { value: "maxity", text: "Maxity" },
    { value: "megane", text: "Megane" },
    { value: "modus", text: "Modus" },
    { value: "nevada", text: "Nevada" },
    { value: "pulse", text: "Pulse" },
    { value: "rEspace", text: "REspace" },
    { value: "rodeo", text: "Rodeo" },
    { value: "safrane", text: "Safrane" },
    { value: "sandero", text: "Sandero" },
    { value: "scala", text: "Scala" },
    { value: "scenic", text: "Scenic" },
    { value: "sportSpider", text: "Sport Spider" },
    { value: "symbol", text: "Symbol" },
    { value: "talento", text: "Talento" },
    { value: "thalia", text: "Thalia" },
    { value: "trafic", text: "Trafic" },
    { value: "twingo", text: "Twingo" },
    { value: "velsatis", text: "Velsatis" },
    { value: "wind", text: "Wind" },
    { value: "zoe", text: "Zoe" },
  ],
  rollsRoyce: [
    {
      value: "make",
      text: "Choose model",
      hidden: true,
    },
    { value: "camargue", text: "Camargue" },
    { value: "corniche", text: "Corniche" },
    { value: "cullinan", text: "Cullinan" },
    { value: "dawn", text: "Dawn" },
    { value: "ghost", text: "Ghost" },
    { value: "parkward", text: "Parkward" },
    { value: "phantom", text: "Phantom" },
    { value: "silverCloud", text: "Silver Cloud" },
    { value: "silverDawn", text: "Silver Dawn" },
    { value: "silverSeraph", text: "Silver Seraph" },
    { value: "silverShadow", text: "Silver Shadow" },
    { value: "silverSpirit", text: "Silver Spirit" },
    { value: "silverSpur", text: "Silver Spur" },
    { value: "wraith", text: "Wraith" },
  ],
  saab: [
    {
      value: "make",
      text: "Choose model",
      hidden: true,
    },
    { value: "9_3", text: "9-3" },
    { value: "9_3X", text: "9-3X" },
    { value: "9_4X", text: "9-4X" },
    { value: "9_5", text: "9-5" },
    { value: "9_7X", text: "9-7X" },
    { value: "900", text: "900" },
    { value: "9000", text: "9000" },
  ],
  saleen: [
    {
      value: "make",
      text: "Choose model",
      hidden: true,
    },
    { value: "S7", text: "S7" },
  ],
  saturn: [
    {
      value: "make",
      text: "Choose model",
      hidden: true,
    },
    { value: "astra", text: "Astra" },
    { value: "aura", text: "Aura" },
    { value: "ion", text: "ION" },
    { value: "l_series", text: "L-Series" },
    { value: "outlook", text: "Outlook" },
    { value: "relay", text: "Relay" },
    { value: "sky", text: "Sky" },
    { value: "vue", text: "Vue" },
  ],
  scion: [
    {
      value: "make",
      text: "Choose model",
      hidden: true,
    },
    { value: "fr_s", text: "FR-S" },
    { value: "ia", text: "iA" },
    { value: "im", text: "iM" },
    { value: "iq", text: "iQ" },
    { value: "tc", text: "tC" },
    { value: "xa", text: "xA" },
    { value: "xb", text: "xB" },
    { value: "xd", text: "xD" },
  ],
  seat: [
    {
      value: "make",
      text: "Choose model",
      hidden: true,
    },
    { value: "124", text: "124" },
    { value: "127", text: "127" },
    { value: "128", text: "128" },
    { value: "131", text: "131" },
    { value: "132", text: "132" },
    { value: "133", text: "133" },
    { value: "600", text: "600" },
    { value: "850", text: "850" },
    { value: "alhambra", text: "Alhambra" },
    { value: "altea", text: "Altea" },
    { value: "arona", text: "Arona" },
    { value: "ateca", text: "Ateca" },
    { value: "cordoba", text: "Cordoba" },
    { value: "exeo", text: "Exeo" },
    { value: "fura", text: "Fura" },
    { value: "ibiza", text: "Ibiza" },
    { value: "ledo", text: "Ledo" },
    { value: "marbella", text: "Marbella" },
    { value: "mii", text: "Mii" },
    { value: "ronda", text: "Ronda" },
    { value: "tarraco", text: "Tarraco" },
    { value: "toledo", text: "Toledo" },
  ],
  skoda: [
    {
      value: "make",
      text: "Choose model",
      hidden: true,
    },
    { value: "100", text: "100" },
    { value: "105", text: "105" },
    { value: "120", text: "120" },
    { value: "130", text: "130" },
    { value: "135", text: "135" },
    { value: "136", text: "136" },
    { value: "Citigo", text: "Citigo" },
    { value: "fabia", text: "Fabia" },
    { value: "favorit", text: "Favorit" },
    { value: "felicia", text: "Felicia" },
    { value: "forman", text: "Forman" },
    { value: "kamiq", text: "Kamiq" },
    { value: "karoq", text: "Karoq" },
    { value: "kodiaq", text: "Kodiaq" },
    { value: "octavia", text: "Octavia" },
    { value: "rapID", text: "Rapid" },
    { value: "roomster", text: "Roomster" },
    { value: "superb", text: "Superb" },
    { value: "yeti", text: "Yeti" },
  ],
  smart: [
    {
      value: "make",
      text: "Choose model",
      hidden: true,
    },
    { value: "forFour", text: "ForFour" },
    { value: "forTwo", text: "ForTwo" },
    { value: "roadster", text: "Roadster" },
  ],
  ssangyong: [
    {
      value: "make",
      text: "Choose model",
      hidden: true,
    },
    { value: "actyon", text: "Actyon" },
    { value: "actyonSports", text: "Actyon Sports" },
    { value: "chairman", text: "Chairman" },
    { value: "korando", text: "Korando" },
    { value: "kyron", text: "Kyron" },
    { value: "musso", text: "Musso" },
    { value: "rexton", text: "Rexton" },
    { value: "rodIus", text: "Rodius" },
    { value: "tivoli", text: "Tivoli" },
    { value: "XLV", text: "XLV" },
  ],
  subaru: [
    {
      value: "make",
      text: "Choose model",
      hidden: true,
    },
    { value: "Baja", text: "Baja" },
    { value: "brat", text: "Brat" },
    { value: "brz", text: "BRZ" },
    { value: "forester", text: "Forester" },
    { value: "Impreza", text: "Impreza" },
    { value: "ImprezaWRX", text: "Impreza WRX" },
    { value: "Justy", text: "Justy" },
    { value: "Legacy", text: "Legacy" },
    { value: "loyale", text: "Loyale" },
    { value: "outback", text: "Outback" },
    { value: "svx", text: "SVX" },
    { value: "tribeca", text: "Tribeca" },
    { value: "vivio", text: "Vivio" },
    { value: "WRX", text: "WRX" },
    { value: "XT", text: "XT" },
    { value: "XV_Crosstrek", text: "XV Crosstrek" },
  ],
  suzuki: [
    {
      value: "make",
      text: "Choose model",
      hidden: true,
    },
    { value: "Aerio", text: "Aerio" },
    { value: "Alto", text: "Alto" },
    { value: "APV", text: "APV" },
    { value: "Cappuccino", text: "Cappuccino" },
    { value: "Carry", text: "Carry" },
    { value: "Celerio", text: "Celerio" },
    { value: "Cervo", text: "Cervo" },
    { value: "Esteem", text: "Esteem" },
    { value: "Every", text: "Every" },
    { value: "forenza", text: "Forenza" },
    { value: "Forsa", text: "Forsa" },
    { value: "grAnd_VitAra", text: "Grand Vitara" },
    { value: "Ignis", text: "Ignis" },
    { value: "Jimny", text: "Jimny" },
    { value: "Kizashi", text: "Kizashi" },
    { value: "Liana", text: "Liana" },
    { value: "lj", text: "LJ" },
    { value: "Samurai", text: "Samurai" },
    { value: "Sidekick", text: "Sidekick" },
    { value: "Splash", text: "Splash" },
    { value: "super_Carry", text: "Super Carry" },
    { value: "Swift", text: "Swift" },
    { value: "SX4", text: "SX4" },
    { value: "Verona", text: "Verona" },
    { value: "Vitara", text: "Vitara" },
    { value: "Wagon_R", text: "Wagon R" },
    { value: "X_90", text: "X-90" },
  ],
  talbot: [
    {
      value: "make",
      text: "Choose model",
      hidden: true,
    },
    { value: "1100", text: "1100" },
    { value: "1307", text: "1307" },
    { value: "1308", text: "1308" },
    { value: "1510", text: "1510" },
    { value: "alpine", text: "Alpine" },
    { value: "horizon", text: "Horizon" },
    { value: "samba", text: "Samba" },
    { value: "solara", text: "Solara" },
    { value: "tagora", text: "Tagora" },
  ],
  tata: [
    {
      value: "make",
      text: "Choose model",
      hidden: true,
    },
    { value: "aria", text: "Aria" },
    { value: "estate", text: "Estate" },
    { value: "indica", text: "Indica" },
    { value: "indigo", text: "Indigo" },
    { value: "nano", text: "Nano" },
    { value: "safari", text: "Safari" },
    { value: "sierra", text: "Sierra" },
    { value: "telco", text: "Telco" },
    { value: "tElcoline", text: "Telcoline" },
    { value: "victa", text: "Victa" },
    { value: "xenon", text: "Xenon" },
    { value: "xover", text: "XOver" },
  ],
  tatra: [
    {
      value: "make",
      text: "Choose model",
      hidden: true,
    },
    { value: "57", text: "57" },
    { value: "77", text: "77" },
    { value: "87", text: "87" },
    { value: "97", text: "97" },
    { value: "600", text: "600" },
    { value: "603", text: "603" },
    { value: "700", text: "700" },
  ],
  tesla: [
    {
      value: "make",
      text: "Choose model",
      hidden: true,
    },
    { value: "roadster", text: "Roadster" },
    { value: "model_S", text: "Model S" },
    { value: "model_3", text: "Model 3" },
    { value: "model_X", text: "Model X" },
    { value: "model_Y", text: "Model Y" },
    { value: "cybertruck", text: "Cybertruck" },
  ],
  toyota: [
    {
      value: "make",
      text: "Choose model",
      hidden: true,
    },
    { value: "4runner", text: "4Runner" },
    { value: "86", text: "86" },
    { value: "aurion", text: "Aurion" },
    { value: "avalon", text: "Avalon" },
    { value: "avensis", text: "Avensis" },
    { value: "aygo", text: "Aygo" },
    { value: "c_hr", text: "C-HR" },
    { value: "camry", text: "Camry" },
    { value: "celica", text: "Celica" },
    { value: "corolla", text: "Corolla" },
    { value: "corolla_Cross", text: "Corolla Cross" },
    { value: "corona", text: "Corona" },
    { value: "cressida", text: "Cressida" },
    { value: "crown", text: "Crown" },
    { value: "echo", text: "Echo" },
    { value: "fj_Cruiser", text: "FJ Cruiser" },
    { value: "fortuner", text: "Fortuner" },
    { value: "GR_86", text: "GR 86" },
    { value: "GT86", text: "GT86" },
    { value: "hiace", text: "Hiace" },
    { value: "highlander", text: "Highlander" },
    { value: "hilux", text: "Hilux" },
    { value: "iq", text: "iQ" },
    { value: "kluger", text: "Kluger" },
    { value: "land_Cruiser", text: "Land Cruiser" },
    { value: "matrix", text: "Matrix" },
    { value: "mr_2", text: "MR2" },
    { value: "paseo", text: "Paseo" },
    { value: "pickup", text: "Pickup" },
    { value: "previa", text: "Previa" },
    { value: "prius", text: "Prius" },
    { value: "prius_C", text: "Prius C" },
    { value: "prius_Plug_in", text: "Prius Plug-in" },
    { value: "prius_Prime", text: "Prius Prime" },
    { value: "prius_V", text: "Prius V" },
    { value: "ractis", text: "Ractis" },
    { value: "rav4", text: "RAV4" },
    { value: "sequoia", text: "Sequoia" },
    { value: "sienna", text: "Sienna" },
    { value: "solara", text: "Solara" },
    { value: "starlet", text: "Starlet" },
    { value: "supra", text: "Supra" },
    { value: "t100", text: "T100" },
    { value: "tacoma", text: "Tacoma" },
    { value: "tundra", text: "Tundra" },
    { value: "venza", text: "Venza" },
    { value: "verso", text: "Verso" },
    { value: "will", text: "Will" },
    { value: "yaris", text: "Yaris" },
  ],
  trabant: [
    {
      value: "make",
      text: "Choose model",
      hidden: true,
    },
    { value: "500", text: "500" },
    { value: "600", text: "600" },
    { value: "601", text: "601" },
    { value: "kombi", text: "Kombi" },
    { value: "p50", text: "P50" },
    { value: "p60", text: "P60" },
  ],
  triumph: [
    {
      value: "make",
      text: "Choose model",
      hidden: true,
    },
    { value: "acclaim", text: "Acclaim" },
    { value: "Dolomite", text: "Dolomite" },
    { value: "GT6", text: "GT6" },
    { value: "herald", text: "Herald" },
    { value: "spitfire", text: "Spitfire" },
    { value: "stag", text: "Stag" },
    { value: "tr2", text: "TR2" },
    { value: "tr3", text: "TR3" },
    { value: "tr3a", text: "TR3A" },
    { value: "tr4", text: "TR4" },
    { value: "tr4a", text: "TR4A" },
    { value: "tr5", text: "TR5" },
    { value: "tr6", text: "TR6" },
    { value: "tr7", text: "TR7" },
    { value: "tr8", text: "TR8" },
    { value: "vitesse", text: "Vitesse" },
  ],
  tvr: [
    {
      value: "make",
      text: "Choose model",
      hidden: true,
    },
    { value: "280i", text: "280i" },
    { value: "350i", text: "350i" },
    { value: "390SE", text: "390SE" },
    { value: "400SE", text: "400SE" },
    { value: "420SE", text: "420SE" },
    { value: "450SE", text: "450SE" },
    { value: "Cerbera", text: "Cerbera" },
    { value: "chimaera", text: "Chimaera" },
    { value: "griffith", text: "Griffith" },
    { value: "s", text: "S" },
    { value: "s2", text: "S2" },
    { value: "s3", text: "S3" },
    { value: "s4", text: "S4" },
    { value: "sagaris", text: "Sagaris" },
    { value: "t350", text: "T350" },
    { value: "tamora", text: "Tamora" },
    { value: "tasmin", text: "Tasmin" },
    { value: "tuscan", text: "Tuscan" },
  ],

  vauxhall: [
    {
      value: "make",
      text: "Choose model",
      hidden: true,
    },
    { value: "adAm", text: "Adam" },
    { value: "agila", text: "Agila" },
    { value: "Ampera", text: "Ampera" },
    { value: "antara", text: "Antara" },
    { value: "astra", text: "Astra" },
    { value: "astravan", text: "Astravan" },
    { value: "calibra", text: "Calibra" },
    { value: "cascada", text: "Cascada" },
    { value: "cavalier", text: "Cavalier" },
    { value: "combo", text: "Combo" },
    { value: "commodore", text: "Commodore" },
    { value: "corsa", text: "Corsa" },
    { value: "crossland_X", text: "Crossland X" },
    { value: "frontera", text: "Frontera" },
    { value: "grandlAnd_X", text: "Grandland X" },
    { value: "Insignia", text: "Insignia" },
    { value: "meriva", text: "Meriva" },
    { value: "mokka", text: "Mokka" },
    { value: "monterey", text: "Monterey" },
    { value: "monza", text: "Monza" },
    { value: "movano", text: "Movano" },
    { value: "nova", text: "Nova" },
    { value: "omega", text: "Omega" },
    { value: "rascal", text: "Rascal" },
    { value: "senator", text: "Senator" },
    { value: "signum", text: "Signum" },
    { value: "sintra", text: "Sintra" },
    { value: "tigra", text: "Tigra" },
    { value: "vivAro", text: "Vivaro" },
    { value: "vivAro_tour", text: "Vivaro Tour" },
    { value: "VXR8", text: "VXR8" },
    { value: "wyvern", text: "Wyvern" },
    { value: "zafira", text: "Zafira" },
  ],
  vector: [
    {
      value: "make",
      text: "Choose model",
      hidden: true,
    },
    { value: "avtechWX3", text: "Avtech WX3" },
    { value: "avtechWX3R", text: "Avtech WX3R" },
    { value: "avtechWX8", text: "Avtech WX8" },
    { value: "M12", text: "M12" },
    { value: "wx3", text: "WX3" },
    { value: "wx3R", text: "WX3R" },
    { value: "wx8", text: "WX8" },
  ],
  venturi: [
    {
      value: "make",
      text: "Choose model",
      hidden: true,
    },
    { value: "200", text: "200" },
    { value: "210", text: "210" },
    { value: "260", text: "260" },
    { value: "300", text: "300" },
    { value: "400", text: "400" },
    { value: "Atlantique", text: "Atlantique" },
    { value: "fetish", text: "Fetish" },
    { value: "grand_tourisme", text: "Grand Tourisme" },
  ],
  volkswagen: [
    {
      value: "make",
      text: "Choose model",
      hidden: true,
    },
    { value: "amarok", text: "Amarok" },
    { value: "arteon", text: "Arteon" },
    { value: "beetle", text: "Beetle" },
    { value: "bora", text: "Bora" },
    { value: "caddy", text: "Caddy" },
    { value: "cc", text: "CC" },
    { value: "corrado", text: "Corrado" },
    { value: "crafter", text: "Crafter" },
    { value: "eos", text: "Eos" },
    { value: "fox", text: "Fox" },
    { value: "golf", text: "Golf" },
    { value: "golf_Alltrack", text: "Golf Alltrack" },
    { value: "golf_Cabrio", text: "Golf Cabrio" },
    { value: "golf_Plus", text: "Golf Plus" },
    { value: "golf_R", text: "Golf R" },
    { value: "golf_Sportsvan", text: "Golf Sportsvan" },
    { value: "golf_GT", text: "Golf GT" },
    { value: "golf_GTD", text: "Golf GTD" },
    { value: "golf_GTE", text: "Golf GTE" },
    { value: "golf_GTI", text: "Golf GTI" },
    { value: "golf_R32", text: "Golf R32" },
    { value: "golf_Variant", text: "Golf Variant" },
    { value: "golf_Variant_GT", text: "Golf Variant GT" },
    { value: "jetta", text: "Jetta" },
    { value: "kaefer", text: "Kaefer" },
    { value: "karmann_Ghia", text: "Karmann Ghia" },
    { value: "lupo", text: "Lupo" },
    { value: "multivan", text: "Multivan" },
    { value: "parati", text: "Parati" },
    { value: "passat", text: "Passat" },
    { value: "passat_Alltrack", text: "Passat Alltrack" },
    { value: "passat_CC", text: "Passat CC" },
    { value: "passat_CL", text: "Passat CL" },
    { value: "passat_Estate", text: "Passat Estate" },
    { value: "passat_GTE", text: "Passat GTE" },
    { value: "phaeton", text: "Phaeton" },
    { value: "pointer", text: "Pointer" },
    { value: "polo", text: "Polo" },
    { value: "routan", text: "Routan" },
    { value: "saveiro", text: "Saveiro" },
    { value: "scirocco", text: "Scirocco" },
    { value: "sharan", text: "Sharan" },
    { value: "t_cross", text: "T-Cross" },
    { value: "taos", text: "Taos" },
    { value: "tarek", text: "Tarek" },
    { value: "tiguan", text: "Tiguan" },
    { value: "tiguan_Allspace", text: "Tiguan Allspace" },
    { value: "touareg", text: "Touareg" },
    { value: "touran", text: "Touran" },
    { value: "up", text: "Up" },
    { value: "vento", text: "Vento" },
  ],
  volvo: [
    {
      value: "make",
      text: "Choose model",
      hidden: true,
    },
    { value: "240", text: "240" },
    { value: "260", text: "260" },
    { value: "340", text: "340" },
    { value: "360", text: "360" },
    { value: "440", text: "440" },
    { value: "460", text: "460" },
    { value: "480", text: "480" },
    { value: "66", text: "66" },
    { value: "740", text: "740" },
    { value: "760", text: "760" },
    { value: "780", text: "780" },
    { value: "850", text: "850" },
    { value: "940", text: "940" },
    { value: "960", text: "960" },
    { value: "c30", text: "C30" },
    { value: "c70", text: "C70" },
    { value: "duett", text: "Duett" },
    { value: "s40", text: "S40" },
    { value: "s60", text: "S60" },
    { value: "s70", text: "S70" },
    { value: "s80", text: "S80" },
    { value: "s90", text: "S90" },
    { value: "v40", text: "V40" },
    { value: "v40_Cross_Country", text: "V40 Cross Country" },
    { value: "v50", text: "V50" },
    { value: "v60", text: "V60" },
    { value: "v60_Cross_Country", text: "V60 Cross Country" },
    { value: "v70", text: "V70" },
    { value: "v90", text: "V90" },
    { value: "v90_Cross_Country", text: "V90 Cross Country" },
    { value: "xc40", text: "XC40" },
    { value: "xc60", text: "XC60" },
    { value: "xc70", text: "XC70" },
    { value: "xc90", text: "XC90" },
  ],
  other: [
    {
      value: "make",
      text: "Choose model",
      hidden: true,
    },
    { value: "other", text: "Other" },
  ],
};
