import './globals.css';
import { Inter } from 'next/font/google';
import { Header } from '@/components/header/Header';
import { Footer } from '@/components/footer/Footer';
import React from "react";
import Sliders from "@/components/slider/Sliders";
import {About} from "@/components/about/About";

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Auto app',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <Sliders />
        <About />
        <main className="container">{children}</main>

        <Footer />
      </body>
    </html>
  );
}
